---
title: "20200220_finalplots"
author: "Casey Sakamoto"
date: "2/20/2020"
output: html_document
---
```{r setup}
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(vegan)
# load in cleaned data
outpatient2v <- read.csv("C:/Users/Casey/Desktop/research/outpatient_2vis.csv")
outpatient2v = outpatient2v %>% select(-X)
# load in MH diversity matrix
Outpatient_MH<- read.delim("C:/Users/Casey/Desktop/research/OutpatientAbx_Morisita-Horn_Morisita-Horn.txt")
```

```{r data clean}
##### mh barchart #####
# load in cleaned data

# -------------------------------------------------------------------------
##### Data Cleaning #####
# get a reference for "name" and "sid"
sid_name_key = outpatient2v %>%select(sid, visit, name)%>% group_by(sid) %>% distinct()

# set the matrix rownames for easier data filtering
rownames(Outpatient_MH) = colnames(Outpatient_MH)

# get the final matrix
MH_final = Outpatient_MH %>% select(levels(sid_name_key$name)) %>%filter(rownames(Outpatient_MH)
                                                                         %in% levels(sid_name_key$name))
rownames(MH_final)=colnames(MH_final)

# create a dictionary-like object
sid_name = as.data.frame(sid_name_key) %>% mutate(sid_vis = paste0(sid,"-",visit)) %>% mutate(sid=NULL, visit=NULL)
sid_name$name = as.character(sid_name$name)
dictionary = sid_name$name
names(dictionary) = sid_name$sid_vis

############## Janky code but it works! 
# take the subid mapping in dictionary
# match it to visits 1 & 2
# find corresponding MH cell in matrix
# return as named list

# still need to delete duplicates so n = 19
y=NULL
for(i in names(dictionary)){
  x = NULL
  a = i
  b = str_split_fixed(a, "-", n=2)
  c = ifelse(grepl(b[1], names(dictionary)),1,0 )
  for(j in 1:38){
    if(c[j]==1){
      p = dictionary[j]
      x = c(x,p)
    } 
  }
  l = MH_final %>% select(x[1]) %>% filter(rownames(MH_final)%in%x[2])
  y = c(y,l)
}
q = as.data.frame(y)

# long format for boxplot
MH_subj = gather(q, key = "Subject", value = "MH-BD",1:38)
MH_subj = MH_subj %>% arrange(Subject) %>% slice(seq(1,37, 2)) 
# get original sid back
firstpart = function(string_vector){
  a = NULL
  for (i in 1:length(string_vector)){
    a[i] = unlist(strsplit(string_vector[i],'.',fixed = TRUE))[1]
  }
  return(a)
}
# final dataframe for boxplot
MH_subj = MH_subj %>% mutate(sid = firstpart(Subject)) %>% rename("MH_BD"=`MH-BD`)%>% select(sid,MH_BD)
# new sid (MH, viral) MH_subj
name_df = outpatient2v %>% filter(visit==1)%>%select(sid, pcr_neg) %>% unique.data.frame()
name_df = full_join(name_df, MH_subj, by = "sid")
name_df = name_df %>% mutate(sid_new = paste0(MH_BD,"_",pcr_neg))
name_df = name_df %>% select(sid, sid_new)
MH_subj = full_join(MH_subj, name_df, by = "sid")
outpatient2v = full_join(outpatient2v, name_df, by= "sid")

```

```{r boxplot}
#### PLOTS #####
MH_subj = MH_subj%>% arrange(MH_subj$MH_BD)

MH_box = ggplot(data = MH_subj, aes(x = "", y = MH_BD, label= sid_new)) + geom_boxplot(outlier.shape = NA) + geom_point()
MH_box = MH_box + labs(title = "Beta Diversity Within Subjects",
                       subtitle = "Visit 1 - Visit 2",
                       x = "", 
                       y = "Morisita-Horn Beta Diversity")

# outside middle 50%
outer_quart = MH_box + geom_label_repel(data = subset(MH_subj,!between(MH_BD,quantile(MH_BD,.25),
                                                                       quantile(MH_BD, .75))),
                                        direction = "x")+theme_classic()

# bottom 25%
lower_quart = MH_box + geom_label_repel(data = subset(MH_subj, MH_BD < quantile(MH_BD, .25)),
                                        direction = "x")+theme_classic()
# save plots
setwd("C:/Repositories/CUANSCHUTZ/2019-2020 Brandie/CF Microbiome")
ggsave("MH_outer_qtls.tiff", plot = outer_quart, dpi = 300)
```

```{r stacked barcharts}
# dropping those without 2 visits
outpatient_cutoff5 = outpatient2v %>% filter(perc_total > 5)

# position for barchart labels
outpatient_cutoff5 = outpatient_cutoff5 %>% group_by(last) %>% mutate(pos = cumsum(perc_total) - (0.5)* perc_total)

# stack labels
taxa_sbc_c5 = ggplot(data = outpatient_cutoff5,
                     aes(x = visit, y = perc_total, fill = last, label = last)) + 
  geom_bar(stat = "identity") + facet_wrap(~sid_new)+
  geom_text(size = 3 , position = position_stack(vjust = 0.5)) 

taxa_sbc_c5 = taxa_sbc_c5 + 
  theme_classic()+
  theme(legend.position = "none")+
  labs(title = "Change in Community Composition Within Subjects",
                                 x = "Visit", 
                                 y = "Total Percent of Community")

setwd("C:/Repositories/CUANSCHUTZ/2019-2020 Brandie/CF Microbiome")
ggsave("20200128_sbc_c5.tiff", plot = taxa_sbc_c5, height = 12, width = 12)
```

```{r spaghetti plots}
##### spaghetti plots #####
library(data.table)
long_op = outpatient2v %>% select(c("sid_new", "visit", "lq_all"))
wide_op = long_op %>% dcast(sid_new~visit, fun=mean) 
long_op = wide_op %>% gather(visit, lq_all, `1`:`2`)
lq_all_noodle = ggplot(data = long_op, 
                       aes(x = as.numeric(visit), y = 10^(lq_all), group = sid_new, label = sid_new)) + 
  geom_line() + 
  scale_y_log10() +
  stat_summary(aes(group = 1), 
               geom = "line", fun.y = mean, color = "blue") 
#geom_text(aes(label = sid), size = 2)
lq_all_noodle = lq_all_noodle + labs(title = "Change in Log Copies/Reaction Within Subjects",
                                     x = "Visit", 
                                     y = "Log Copies per Reaction") + theme_classic()

lq_all_noodle = lq_all_noodle  + geom_label_repel(point.padding = NA,
                                                  #direction = "y",
                                                  size = 2)
#print(lq_all_noodle)
setwd("C:/Repositories/CUANSCHUTZ/2019-2020 Brandie/CF Microbiome")
ggsave("20200128_spaghetti_plot.tiff", plot = lq_all_noodle, height = 12, width = 12)

## TBL differences
wide_op = wide_op %>% mutate(load_diff = wide_op$`2` - wide_op$`1`)

wide_op %>% filter(load_diff > 0.5) %>% count() # 6 > 0.5
wide_op %>% filter(load_diff < -0.5) %>% count() # 5 < -0.5
wide_op %>% filter(abs(load_diff) < 0.5) %>% count()
```

