---
title: "Strep Model Plots"
author: "Casey Sakamoto"
date: "7/1/2020"
output: pdf_document
---

```{r setup, include=FALSE}
# load packages
library(tidyverse)
library(lcmm)
library(ggalluvial) # visualizing the class movements
library(Hmisc)
# load in models from strep models
load("C:/Users/Casey/Desktop/FinalStrep.RData")
describe(BONUS_al3$Age)
describe(BONUS_al3$agemos)
describe(BONUS_al3$X_zlen)
describe(BONUS_al3$Streptococcus)


```

```{r trajectories}
summarytable(clrmod_3_spl_1,clrmod_3_spl_2,clrmod_3_spl_3,clrmod_3_spl_4, which = c("G", "loglik", "npm", "AIC", "BIC", "%class"))
# look at the trajectories of the 4 lc fit in the splines model
postprob(clrmod_3_spl_2)
postprob(clrmod_3_spl_3) # splits up class 2 into two parts; class 1 in prev model = class 2 in this
postprob(clrmod_3_spl_4) # looks like some of the big class is being split up

#plotfit
plot(clrmod_3_spl_4)

# class 1 n = 30 black, 2 n = 4 red, 3n = 103 green, 4n = 55 blue

plot(clrmod_3_spl_4, which = "fit", var.time = "Age",
     xlab = "age", ylab = "normalized strep",  bty = "l", break.times = c(1,2,3,4,5,6,8,10,12), ylim = c(-6,2.5))
# posterior probabilities
postprob(clrmod_3_spl_4)

# predicted trajectories
data_pred = data.frame(Age=seq(1,12, length.out = 100))
pred = predictY(clrmod_3_spl_4, data_pred, var.time = "Age", break.times = c(1,2,3,4,5,6,8,10,12))
plot(pred, ylab = "Normalized Streptococcus RA", main = "Class-speccific Mean Predicted Trajectory")

describe(BONUS_al3$Streptococcus)
```

```{r traj natural scale}
# plot our models in the natural RA scale for kirk
BONUS_Species <- read.delim("C:/Users/Casey/Desktop/WorkData/Thesis 2020/BONUS_Species.txt")

# groups
BONUS_Species =  BONUS_Species %>% mutate(taxa_group = case_when(grepl("Veillonella", OTU_Name) ~ "Veillonella",
                                                                 grepl("Streptococcus", OTU_Name) ~ "Streptococcus",
                                                                 grepl("Prevotella", OTU_Name) ~ "Prevotella",
                                                                 grepl("Neisseria", OTU_Name) ~ "Neisseria",
                                                                 TRUE ~ "Other"))
# get ra and put in in our dataset
groups = BONUS_Species %>% select(taxa_group, seq_count, molecular_id,perc_total, Patient, Age, agemos,Num_Samples) %>% filter(Num_Samples > 2) %>% filter(!(molecular_id == "C02613" & agemos < 4.8)) %>% unique.data.frame()

groups = groups %>% group_by(taxa_group, molecular_id) %>% summarise(ra = sum(perc_total)) # 5155/5 = 1031 = # samples
ra_strep = groups %>% filter(taxa_group == "Streptococcus");# rm(groups)

classes4 = clrmod_3_spl_4$pprob[,1:2] %>% rename(class4 = class)
BONUS_al3 = full_join(BONUS_al3, classes4, by = "patient_id"); rm(classes4)
BONUS_al3 = full_join(BONUS_al3, ra_strep, by = "molecular_id"); rm(ra_strep)

# plots
ggplot(data = BONUS_al3) + geom_line(aes(x = Age, y = ra, group = patient_id)) + facet_wrap(~as.factor(class4)) + theme_classic() + ggtitle( "Subject Streptococcus Trajectory") + ylab("Streptococcus Relative Abundance")

ggplot(data = BONUS_al3) + geom_point(aes(x = Age, y = ra, group = patient_id)) + facet_wrap(~as.factor(class4)) + theme_classic() + ggtitle( "Subject Streptococcus Trajectory") + ylab("Streptococcus Relative Abundance") + geom_smooth(aes(x = Age, y = ra),method = "loess", se = F)
```

```{r alluvial}
classes2 = clrmod_3_spl_2$pprob[,1:2] %>% rename(class2 = class) # to get the classes for alluvial plots
classes3 = clrmod_3_spl_3$pprob[,1:2] %>% rename(class3 = class)
classes4 = clrmod_3_spl_4$pprob[,1:2] %>% rename(class4 = class)


# make data frame for the classes
alluvial_df = full_join(classes2, classes3, by = "patient_id")
alluvial_df = full_join(alluvial_df, classes4, by = "patient_id")

# put into aluvial form
alluvial_df = alluvial_df %>% group_by(class2,class3,class4) %>% summarise( freq=n())
is_alluvia_form(alluvial_df, silent = T)

# ggplot
lc_alluvial = ggplot(alluvial_df, aes(y = freq, axis1 = as.factor(class2), axis2 = as.factor(class3), axis3 = as.factor(class4))) + 
  geom_alluvium(aes(fill = as.factor(class4)),width = 1/20) + geom_stratum(width = 1/6, alpha = 0.5) +
  geom_label(stat = "stratum",infer.label = TRUE) + scale_x_discrete(limits = c("2 LC", "3 LC", "4 LC"), expand = c(0.05, 0.05)) + 
  scale_fill_brewer(type = "qual", palette = "Dark2") + ggtitle("Latent Class Models 2-4") + theme_classic() + ylab("Frequency")

### need to look at what the trajectories are like and assign labels to the groups to better understand what is happening
lc_alluvial

setwd("C:/Users/Casey/Desktop/WorkData/Thesis 2020")
ggsave("lcmm_alluvial.png", plot = lc_alluvial, width = 9, height = 7)
```

```{r covariate models}

# merge groups with data frame
merger = clrmod_3_spl_4$pprob[,1:2]
colnames(merger) = c("patient_id", "latent_class")
BONUS_al3 = full_join(merger, BONUS_al3, by = "patient_id"); rm(merger)


ggplot(data = BONUS_al3, aes(Age, Streptococcus,)) + geom_point(aes(color = factor(latent_class))) + scale_color_manual(values = c("black","red","green","blue")) + geom_smooth(method = loess, se = F) + theme_classic()
# base model using only age
# covariates we are interested in:
# constant over time: Class: genotype (class) gender (sex_std) meconium ileus (mic_il) age first abx (Age_firstabx)
# time varying: Feeding type (Feed), weight& height zscore (X_zwei, X_zlen), abx status (curr_on), # abx on (On), cumulative abx days (cum)

#problems fitting lcmm w covariates so we'll do a second stage analysis comparing covariates across groups for selection
# weight
summary(aov(latent_class~X_zwei,data = BONUS_al3)) # not significant 
# gender
chisq.test(table(BONUS_al3$latent_class, BONUS_al3$sex_std)) # sig, fine table
# genotype
fisher.test(table(BONUS_al3$latent_class, BONUS_al3$class), workspace = 2e8) # not sig, low table counts
# mic_il
fisher.test(table(BONUS_al3$latent_class, BONUS_al3$mic_il)) # sig
# age first abx
summary(aov(latent_class~age_firstabx,data = BONUS_al3)) # significant
# feed
fisher.test(table(BONUS_al3$latent_class, BONUS_al3$feed), workspace = 2e8) # sig
# abx status
fisher.test(table(BONUS_al3$latent_class, BONUS_al3$curr_on)) # sig
# number abx on
summary(aov(latent_class~on,data = BONUS_al3)) #sig
# cumulative abx days
summary(aov(latent_class~cum,data = BONUS_al3)) # sig

#looks like important ones are gender, genotype, meconium ileus, age first abx, feed, abx status, cumulative daysabx--- 3 lc new mod


#######
describe(BONUS_al3)
# cts
pairs(~Streptococcus+X_zwei+X_zlen+age_firstabx + cum, data = BONUS_al3) # zwei & zlen correlated. might use just one
stats::cor(BONUS_al3$X_zlen, BONUS_al3$X_zwei, use = "complete.obs", method = "spearman") # 0.7 corr
stats::cor(BONUS_al3$Streptococcus, BONUS_al3$X_zwei, use = "complete.obs",  method = "spearman") # 0.27
stats::cor(BONUS_al3$Streptococcus, BONUS_al3$X_zlen, use = "complete.obs", method = "spearman") # 0.13

# we'll use weight?
# discrete
pairs(Streptococcus~ class + sex_std + cum + curr_on + on + feed, data = BONUS_al3)


### model
# model the right way? doesnt converge with 30 rep at 15 iter, going to try and up it to see if it converges
# with up to 50 and 200 models take 20 sec per iter and doenst meet 2nd deriv or lieklihood criteria
cov_init_mod = lcmm(Streptococcus ~ Age,
                    random = ~ Age, ng = 1, link = "5-quant-splines", subject = "patient_id", data = BONUS_al3)
# runs with class
model_aim2 = gridsearch(
                             lcmm(Streptococcus ~ Age,
                             classmb = ~ feed,
                             random = ~ Age, subject = "patient_id",
                             ng = 4,
                             mixture = ~ Age,
                             link = "5-quant-splines", data = BONUS_al3),
                        rep = 15, maxiter =30, minit = cov_init_mod)
summary(model_aim2)
plot(model_aim2, which = "fit", var.time = "Age", break.times = c(1,2,3,4,5,6,8,10,12),legend = NULL)
```


```{r feeding figures}

# put lc in feeding data set
classes4 = clrmod_3_spl_4$pprob[,1:2] %>% rename(class4 = class)
BONUS_al3 = full_join(BONUS_al3, classes4, by = "patient_id")
BONUS_al3 %>% group_by(feed, Age,class4) %>% summarise(n = n())
# scatter for strep v age w/ curve for fdg type?
feed_scatter = ggplot(aes(x = Age, y = Streptococcus, group = Patient), data = BONUS_al3) + facet_wrap(~class4) + geom_point(aes(shape = feed, color = feed)) #+ geom_line(aes(color = feed))

# feed barchart
feed_bar_1 = ggplot(aes(x = factor(class4), fill = factor(feed)),data = BONUS_al3) + facet_wrap(~factor(Age)) + geom_bar(position = "fill") +
  labs(title = "Feeding Types by Age and Latent Class", x = "Latent Class", y = "Proportion" ) + scale_fill_discrete(name = "Feeding Type")
feed_bar_1

feed_bar_2 = ggplot(aes(x = factor(feed), fill = factor(class4)),data = BONUS_al3) + facet_wrap(~factor(Age)) + geom_bar(position = "fill") 
feed_bar_2
setwd("C:/Users/Casey/Desktop")
ggsave("feed_scatter.png",plot = feed_scatter, height = 10, width = 10)
ggsave("feed_bar.png",plot = feed_bar, height = 10, width = 10)
```